# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "BB-8 Documentation"
theme: just-the-docs
color_scheme: "dark"
search_enabled: true
tagline: The documentation site for BB-8.
description: > # this means to ignore newlines until "baseurl:"
  The documentation site for BB-8.
encoding: utf-8

# Build settings
markdown: kramdown
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
#plugins:
#  - jekyll-feed

# just-the-docs specific
heading_anchors: true
footer_content: "BB-8 Documentation created by Finch | Bot created and provided by kennnyshiwa#1337 | Support BB-8 on Patreon to get a custom adventure item https://www.patreon.com/kennnyshiwa!"
logo: "/assets/js/images/bb8.png"

# Aux links for the upper right navigation
aux_links:
  "Invite Me!":
    - "https://discordapp.com/oauth2/authorize?client_id=540694922307698690&scope=bot&permissions=2146958839"
  "Support Server":
    - "https://discord.com/invite/TEeXcDY"
  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/